server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # =========================
    # FRONTEND REACT
    # =========================
    location / {
        try_files $uri /index.html;
    }

    # =========================
    # API BACKEND
    # =========================
    location /api/lumen/ {
        proxy_pass http://lumen-backend:9000/api/lumen/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # =========================
    # SECURITY HEADERS (IMPORTANT FIX CSP)
    # =========================
    add_header Content-Security-Policy "
        default-src 'self';
        img-src 'self' data: blob:;
        media-src 'self' blob:;
        script-src 'self' 'unsafe-inline';
        style-src 'self' 'unsafe-inline';
    " always;
}