FROM node:20-alpine
WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm install

# Copier le code
COPY . .

# Exposer le port dev
EXPOSE 3000

# Lancer le serveur dev
CMD ["npm", "start"]